#!/usr/bin/env bash

DEST_DIR=$1
echo $SRC_DIR 1>&2
echo $BUILD_ID 1>&2
echo $BUILD_NAME 1>&2
echo $BUILD_JOB_NAME 1>&2
echo $BUILD_PIPELINE_NAME 1>&2
echo $ATC_EXTERNAL_URL 1>&2

PLATFORM=`uname`

SCRIPT_INPUT='/tmp/input'
cat > $SCRIPT_INPUT <&0 # STDIN params

SERVER=$(jq -r '(.source.servers + [.source.server])[0]' < $SCRIPT_INPUT)
PORT=$(jq -r '.source.port // ""' < $SCRIPT_INPUT)
BASE_DIR=$(jq -r '.source.base_dir // ""' < $SCRIPT_INPUT)
USER=$(jq -r '.source.user // ""' < $SCRIPT_INPUT)
VERSION=$(jq -r '.version.ref // ""' < $SCRIPT_INPUT)
jq -re '.source.disable_version_path' < $SCRIPT_INPUT >/dev/null
# a little tricky: 0 is the status code that says that we found the entry.  It's inverted logic.
DISABLE_VERSION_PATH=$?

## check if port is set in the configuration and
## use default SSH port number 22 otherwise
if [ -z "$PORT" ]; then
    PORT=22
fi

echo $SCRIPT_INPUT 1>&2
echo $SERVER    1>&2
echo $PORT      1>&2
echo $BASE_DIR  1>&2
echo $USER      1>&2
echo $VERSION   1>&2

mkdir -p ~/.ssh
(jq -r '.source.private_key // empty' < $SCRIPT_INPUT) > ~/.ssh/server_key
echo -e "Host $SERVER\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
chmod -R 600 ~/.ssh

eval $(ssh-agent) 1>&2 >/dev/null
SSH_ASKPASS=/opt/resource/askpass.sh DISPLAY= ssh-add ~/.ssh/server_key 1>&2 >/dev/null

if [ "$DISABLE_VERSION_PATH" -eq "0" ]
then
    # any version is already rolled in
    SRC_DIR=$BASE_DIR
else
    SRC_DIR=$BASE_DIR/$VERSION
fi

echo $SRC_DIR 1>&2

if [[ -z "$VERSION" && "$DISABLE_VERSION_PATH" -eq "1" ]]; then
  echo "ERROR Version specification $VERSION invalid!" 1>&2
  exit 1
else
  if (ssh -t -i ~/.ssh/server_key -p $PORT $USER@$SERVER '[ -d $SRC_DIR ]' ); then
    RSYNC_CMD="rsync -Pav -e 'ssh -i ~/.ssh/server_key -p $PORT' $USER@$SERVER:$SRC_DIR/* $DEST_DIR"
    echo $RSYNC_CMD  1>&2
    eval $RSYNC_CMD  1>&2
    if [ $? -eq 0 ]; then
        TIMESTAMP=$(find $DEST_DIR -type f -exec stat -c "%Y" {} \; | sort -n | tail -1)
        OUTPUT_STRING="{ \"version\": { \"ref\": \"$TIMESTAMP\"} }"
        echo $OUTPUT_STRING
        exit 0
    else
      echo "Failed to rsync $SRC_DIR to $DEST_DIR" 1>&2
      exit 1
    fi
  else
    echo "Version $VERSION no longer available in $BASE_DIR" 1>&2
    exit 1
  fi
fi
