#!/usr/bin/env bash

SRC_DIR=$1
CONCOURSE_SHARE_BASE='/mnt/concourse_share'
echo $SRC_DIR 1>&2
echo $BUILD_ID 1>&2
echo $BUILD_NAME 1>&2
echo $BUILD_JOB_NAME 1>&2
echo $BUILD_PIPELINE_NAME 1>&2
echo $ATC_EXTERNAL_URL 1>&2

SCRIPT_INPUT_JSON=''
while read LINE
do
  SCRIPT_INPUT_JSON=$SCRIPT_INPUT_JSON$LINE
done

echo $SCRIPT_INPUT_JSON 1>&2


if [ -e $CONCOURSE_SHARE_BASE ]; then

  VERSION_STRING="$BUILD_PIPELINE_NAME-$BUILD_ID"
  MD5_STRING=`md5 -s $VERSION_STRING | rev | cut -d ' ' -f 1 | rev`
  if [ $? -eq 0 ]; then
    echo $MD5_STRING 1>&2

    # Create the new directory for this build
    DEST_DIR=$CONCOURSE_SHARE_BASE/$MD5_STRING
    mkdir -p $DEST_DIR
    if [ $? -eq 0 ]; then
      rsync -av $SRC_DIR $DEST_DIR 1>&2
      if [ $? -eq 0 ]; then
          OUTPUT_STRING="{ \"version\": { \"ref\": \"$MD5_STRING\"},}"
          echo $OUTPUT_STRING
          exit 0
      else
        echo "Failed to rsync $SRC_DIR to $DEST_DIR" 1>&2
        exit 1
      fi
    else
      echo "Failed to create destination $DEST_DIR" 1>&2
      exit 1
    fi

  else
    echo "Failed to create MD5 hash"
    exit 1
  fi

else
  echo "No /mnt/concourse_share directory found" 1>&2
  exit 1
fi
