name: Tag

on:
  pull_request:
    types: [closed]
    branches: [master]

jobs:
  tag:
    name: Create version tag
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
          custom_release_rules: "feat:minor,fix:patch,docs:patch,refactor:patch,test:patch,chore:patch,ci:patch"
